---
- hosts: host1
  become: yes
  tasks:
     - include_tasks: pkg_{{ ansible_os_family }}.yml
       when: ansible_facts['os_family'] == "{{ ansible_os_family }}"
     - include_vars: var.yml
     - name: create user
       user:
               name: "{{ a1 }}"
               state: present


