---
- hosts: host1
  become: yes
  tasks:
    - name: Run with items greater than 5
      ansible.builtin.command: echo {{ item }} > /home/ubuntu/test.txt
      loop: [ 0, 2, 4, 6, 8, 10 ]
      when: item > 5
